// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"cribl-demo/pkg/models/shared"
	"net/http"
)

type CreateCertificateResponse struct {
	// Created
	Certificate *shared.Certificate
	ContentType string
	// Unexpected error
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
