// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Error - Unexpected error
type Error struct {
	// Error message
	Message *string `json:"message,omitempty"`
}
